source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 2.6.4'

gem 'rack', '= 2.0.8'
gem 'rack-ssl', '= 1.4.1'
gem 'rack_csrf', '= 2.6.0'
gem 'rack-contrib', '= 2.1.0'

gem 'unicorn', '= 5.5.1'
gem 'sinatra', '= 2.0.7'
gem 'sinatra-flash', '= 0.3.0'
gem 'sinatra-namespace', '= 1.0'
gem 'rails', '= 6.0.1'

gem 'bootsnap', '= 1.4.5', require: false

gem 'jbuilder', '= 2.9.1' # build json APIs
gem 'sass-rails', '= 6.0.0'
gem 'bootstrap-sass', '= 3.4.1'
gem 'sprockets', '= 4.0.0'
gem 'sprockets-rails', '= 3.2.1', require: 'sprockets/railtie'
gem 'uglifier', '= 4.2.0'

gem 'aws-sdk-s3', '= 1.53.0'
gem 'aws-sdk-ses', '= 1.27.0'

gem 'httparty', '0.21.0'

# DataMapper libraries
gem 'eigenclass', '= 2.0.4'
gem 'data_objects', '= 0.10.17'
gem 'do_mysql', '= 0.10.17'
gem 'dm-core', '= 1.2.1'
gem 'dm-types', :github => 'jpr5/dm-types', :branch => 'v1.2.2'
gem 'dm-timestamps', '= 1.2.0'
gem 'dm-validations', '= 1.2.0'
gem 'dm-serializer', '= 1.2.2'
gem 'dm-aggregates', '= 1.2.0'
gem 'dm-ar-finders', '= 1.2.0'
gem 'dm-migrations', '= 1.2.0'
gem 'dm-transactions', '= 1.2.0'
gem 'dm-do-adapter', '= 1.2.0'
gem 'dm-mysql-adapter', '= 1.2.0'

gem 'avatax', '= 19.9.1'
gem 'activemerchant', '= 1.104.0'

#gem 'delayed_job_data_mapper'

group :development, :test do
    gem 'irb', '= 1.2.1'
    gem 'byebug', '= 11.0.1'
    gem 'pry', '= 0.12.2'
end

group :development do
    gem 'web-console', '= 4.0.1'
    gem 'listen', '= 3.1.5'
end

group :test do
    gem "rspec", '= 3.9.0'
    gem 'cucumber', '= 3.1.2'
    gem 'cucumber-rails', '= 2.0.0', require: false

    # Adds support for Capybara system testing and selenium driver
    gem 'capybara', '= 3.29.0'
    gem 'selenium-webdriver', '= 3.142.6'

    # Easy installation and use of web drivers to run system tests with browsers
    gem 'webdrivers', '= 4.1.3'
end
